/*
Deployment script for JuegosCompletados

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "JuegosCompletados"
:setvar DefaultFilePrefix "JuegosCompletados"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Juegos]...';


GO
CREATE TABLE [dbo].[Juegos] (
    [Id]            INT          IDENTITY (1, 1) NOT NULL,
    [Nombre]        VARCHAR (50) NULL,
    [Completado]    VARCHAR (50) NULL,
    [Cienporciento] VARCHAR (50) NULL,
    [Logros]        VARCHAR (50) NULL,
    [Cantidad]      INT          NULL,
    [Nota]          INT          NULL,
    [Fecha]         DATETIME     NULL
);


GO
PRINT N'Creating Procedure [dbo].[spActualizarJuego]...';


GO
CREATE PROCEDURE spActualizarJuego
    @Id INT,
    @Nombre NVARCHAR(50),
    @Completado NVARCHAR(50),
    @Cienporciento NVARCHAR(50),
    @Logros NVARCHAR(50),
    @Cantidad INT,
    @Nota INT,
    @Fecha DATETIME
AS
BEGIN
    UPDATE Juegos
    SET Nombre = @Nombre,
        Completado = @Completado,
        Cienporciento = @Cienporciento,
        Logros = @Logros,
        Cantidad = @Cantidad,
        Nota = @Nota,
        Fecha = @Fecha
    WHERE Id = @Id
END
GO
PRINT N'Creating Procedure [dbo].[spBorrarJuego]...';


GO
CREATE PROCEDURE spBorrarJuego
    @Id INT
AS
BEGIN
    DELETE FROM Juegos WHERE Id = @Id
END
GO
PRINT N'Creating Procedure [dbo].[spGetJuegos]...';


GO
CREATE PROCEDURE spGetJuegos
    @Buscar NVARCHAR(50) = NULL
AS
BEGIN
    SELECT Id, Nombre, Completado, Cienporciento, Logros, Cantidad, Nota, Fecha 
    FROM Juegos
    WHERE @Buscar IS NULL OR
          Nombre LIKE '%' + @Buscar + '%' OR
          Completado LIKE '%' + @Buscar + '%' OR
          Cienporciento LIKE '%' + @Buscar + '%' OR
          Logros LIKE '%' + @Buscar + '%' OR
          Cantidad LIKE '%' + @Buscar + '%' OR
          Nota LIKE '%' + @Buscar + '%' OR
          Fecha LIKE '%' + @Buscar + '%'
END
GO
PRINT N'Creating Procedure [dbo].[spInsertarJuego]...';


GO
CREATE PROCEDURE spInsertarJuego
    @Nombre NVARCHAR(50),
    @Completado NVARCHAR(50),
    @Cienporciento NVARCHAR(50),
    @Logros NVARCHAR(50),
    @Cantidad INT,
    @Nota INT,
    @Fecha DATETIME
AS
BEGIN
    INSERT INTO JUEGOS(Nombre, Completado, Cienporciento, Logros, Cantidad, Nota, Fecha)
    VALUES (@Nombre, @Completado, @Cienporciento, @Logros, @Cantidad, @Nota, @Fecha)
END
GO
PRINT N'Update complete.';


GO
